export const makeColorNode = function (label?: string, title?: string) {
	return makeStringNode(
		[
			"inherit",
			"-moz-initial",
			"initial",
			"revert",
			"revert-layer",
			"unset",
			"aliceblue",
			"antiquewhite",
			"aqua",
			"aquamarine",
			"azure",
			"beige",
			"bisque",
			"black",
			"blanchedalmond",
			"blue",
			"blueviolet",
			"brown",
			"burlywood",
			"cadetblue",
			"chartreuse",
			"chocolate",
			"coral",
			"cornflowerblue",
			"cornsilk",
			"crimson",
			"cyan",
			"darkblue",
			"darkcyan",
			"darkgoldenrod",
			"darkgray",
			"darkgreen",
			"darkgrey",
			"darkkhaki",
			"darkmagenta",
			"darkolivegreen",
			"darkorange",
			"darkorchid",
			"darkred",
			"darksalmon",
			"darkseagreen",
			"darkslateblue",
			"darkslategray",
			"darkslategrey",
			"darkturquoise",
			"darkviolet",
			"deeppink",
			"deepskyblue",
			"dimgray",
			"dimgrey",
			"dodgerblue",
			"firebrick",
			"floralwhite",
			"forestgreen",
			"fuchsia",
			"gainsboro",
			"ghostwhite",
			"gold",
			"goldenrod",
			"gray",
			"green",
			"greenyellow",
			"grey",
			"honeydew",
			"hotpink",
			"indianred",
			"indigo",
			"ivory",
			"khaki",
			"lavender",
			"lavenderblush",
			"lawngreen",
			"lemonchiffon",
			"lightblue",
			"lightcoral",
			"lightcyan",
			"lightgoldenrodyellow",
			"lightgray",
			"lightgreen",
			"lightgrey",
			"lightpink",
			"lightsalmon",
			"lightseagreen",
			"lightskyblue",
			"lightslategray",
			"lightslategrey",
			"lightsteelblue",
			"lightyellow",
			"lime",
			"limegreen",
			"linen",
			"magenta",
			"maroon",
			"mediumaquamarine",
			"mediumblue",
			"mediumorchid",
			"mediumpurple",
			"mediumseagreen",
			"mediumslateblue",
			"mediumspringgreen",
			"mediumturquoise",
			"mediumvioletred",
			"midnightblue",
			"mintcream",
			"mistyrose",
			"moccasin",
			"navajowhite",
			"navy",
			"oldlace",
			"olive",
			"olivedrab",
			"orange",
			"orangered",
			"orchid",
			"palegoldenrod",
			"palegreen",
			"paleturquoise",
			"palevioletred",
			"papayawhip",
			"peachpuff",
			"peru",
			"pink",
			"plum",
			"powderblue",
			"purple",
			"rebeccapurple",
			"red",
			"rosybrown",
			"royalblue",
			"saddlebrown",
			"salmon",
			"sandybrown",
			"seagreen",
			"seashell",
			"sienna",
			"silver",
			"skyblue",
			"slateblue",
			"slategray",
			"slategrey",
			"snow",
			"springgreen",
			"steelblue",
			"tan",
			"teal",
			"thistle",
			"tomato",
			"transparent",
			"turquoise",
			"violet",
			"wheat",
			"white",
			"whitesmoke",
			"yellow",
			"yellowgreen",
			"ActiveBorder",
			"ActiveCaption",
			"AppWorkspace",
		],
		label,
		title
	);
};

export const makeNumberNode = function (label?: string, title?: string) {
	return makeStringNode([], label, title);
};

export const makeBlockNode = function (label?: string, title?: string) {
	return makeStringNode(
		[
			"hidden",
			"none",
			"inherit",
			"-moz-initial",
			"initial",
			"revert",
			"revert-layer",
			"unset",
			"dashed",
			"dotted",
			"double",
			"groove",
			"inset",
			"outset",
			"ridge",
			"solid",
		],
		label,
		title
	);
};

export const make4Params = function (label?: string, title?: string) {
	return makeStringNode(["auto", "0px", "0px 0px", "0px 0px 0px 0px"], label, title);
};

export const makeRepeatNode = function (label?: string, title?: string) {
	return makeStringNode(["inherit", "-moz-initial", "initial", "revert", "revert-layer", "unset", "stretch", "repeat", "round", "space"], label, title);
};

export const makeStringNode = function (enumString: string[], label: string = "", title: string = "") {
	return {
		//详细介绍
		label: label,
		//标题，一般来说是对当前字段英文名的中文翻译
		title: title,
		propDefineNode: true,
		propType: "string",
		propEnums: enumString,
	};
};

export const makeBooleanNode = function (label: string = "", title: string = "") {
	return {
		label: label,
		//标题，一般来说是对当前字段英文名的中文翻译
		title: title,
		propDefineNode: true,
		propType: "boolean",
		propEnums: [true, false],
	};
};
